### ISSUE TITLE
Proxy Problem

### ISSUE THREAD

**Issue by oguzdelioglu** [dailymotion/dailymotion-sdk-php#59] opened 2018-11-22 02:03 UTC
Uncaught DailymotionAuthException: Invalid token server response

Proxy Upload cannot success.

Please help me.

**Comment by nicoferron** [comment] 2018-11-22 13:54
Hello @oguzdelioglu,

Did you had a message written with this error ?
When it occur ?
Can you give us a sample code ?

Regards,
Dailymotion team.

**Comment by oguzdelioglu** [comment] 2018-11-22 14:14
`$videocategory = $islemler["katdeger"];
$videotags = $islemler["videotags"];
$videodescription = $islemler["videodescription"];
$api = new Dailymotion();
$api->debug = true;
$api->connectionTimeout = 20000;
if(!empty($proxy["ip"]) AND !empty($proxy["port"])) $api->proxy = $proxy["ip"].":".$proxy["port"];
if(!empty($proxy["user"]) AND !empty($proxy["pass"])) $api->proxyCredentials = $proxy["user"].":".$proxy["pass"];
$timeoutx = $api->timeout = 20000; //set higher for slow proxies.
$api->setGrantType(Dailymotion::GRANT_TYPE_PASSWORD,$apikey,$apisecret,array('read', 'write', 'delete', 'manage_videos'),
array('username' => $username, 'password' => $password)
);
try
{
  $url = $api->uploadFile($videofile);
  $result = $api->call('video.create', array('url' => $url, 'title' => $videotitle , 'channel' => $videocategory , 'tags' => $videotags, 'description' => $videodescription, 'published' => true));
  $videourl = 'http://www.dailymotion.com/video/'.$result['id'];
}
catch (DailymotionAuthRequiredException $e)
{
}
catch (DailymotionAuthRefusedException $e)
{
}`


Result php

[https://api.dailymotion.com/oauth/token] >>> grant_type=password&client_id=85d31f49e014fcb19018&client_secret=39a375b1f954275f99a4c63eb929f74748f902dc&scope=read+write+delete+manage_videos&username=root&password=Km820200%40 <<< [https://api.dailymotion.com/oauth/token] <<< HTTP/1.1 200 OK Content-Security-Policy-Report-Only: default-src https: blob: wss: data: android-webview-video-poster: android-webview: chrome-extension: safari-extension: 'unsafe-eval' 'unsafe-inline'; report-uri https://www.dailymotion.com/content_security_policy_report_uri Server: DMS/1.0.42 X-DM-BackNode: web-445.adm.dc3.dailymotion.com:80 Vary: X-DM-SSL Cache-Control: no-store, stale-if-error=900 Content-Type: application/json Content-Security-Policy: upgrade-insecure-requests Access-Control-Expose-Headers: X-DM-BackNode-Response-Time Date: Thu, 22 Nov 2018 14:13:32 GMT X-DM-LB-IP: 195.8.215.129 X-DM-LB-Name: lb-07 X-DM-Random-Number: 3990912 X-DM-BackNode-Response-Time: 145 X-DM-Cache-Status: MISS X-Protected-By: Sqreen X-Dm-Page: ru.html.api_oauth_token X-DM-Edge: DMParis Content-Length: 68 {"error":"invalid_grant","error_description":"Invalid credentials."}
Fatal error: Uncaught DailymotionAuthException: Invalid token server response: HTTP/1.1 200 OK Content-Security-Policy-Report-Only: default-src https: blob: wss: data: android-webview-video-poster: android-webview: chrome-extension: safari-extension: 'unsafe-eval' 'unsafe-inline'; report-uri https://www.dailymotion.com/content_security_policy_report_uri Server: DMS/1.0.42 X-DM-BackNode: web-445.adm.dc3.dailymotion.com:80 Vary: X-DM-SSL Cache-Control: no-store, stale-if-error=900 Content-Type: application/json Content-Security-Policy: upgrade-insecure-requests Access-Control-Expose-Headers: X-DM-BackNode-Response-Time Date: Thu, 22 Nov 2018 14:13:32 GMT X-DM-LB-IP: 195.8.215.129 X-DM-LB-Name: lb-07 X-DM-Random-Number: 3990912 X-DM-BackNode-Response-Time: 145 X-DM-Cache-Status: MISS X-Protected-By: Sqreen X-Dm-Page: ru.html.api_oauth_token X-DM-Edge: DMParis Content-Length: 68 {"error":"invalid_grant","error_description":"Invalid credentials."} in C:\laragon\www\modules\sdk\Dailymotion.php:732 Stack tra in C:\laragon\www\modules\sdk\Dailymotion.php on line 732

**Comment by nicoferron** [comment] 2018-11-22 14:59
Can you remove your username and password values on your post (and maybe change them now)?

It looks like your $username and $password have wrong value because dailymotion's usernames have to be an email.

Regards,
Dailymotion team.

**Comment by oguzdelioglu** [comment] 2018-11-22 15:02
> Can you remove your username and password values on your post (and maybe change them now)?
> 
> It looks like your $username and $password have wrong value because dailymotion's usernames have to be an email.
> 
> Regards,
> Dailymotion team.

I can upload without proxy.

When I use a proxy, the result is as above.

**Comment by SuperToma** [comment] 2018-11-22 15:11
Hi @oguzdelioglu,

I think your variables $login and $password are override with your proxy credentials.

Can you check in your code that the names of these variables are not the same for the dailymotion authentification and the proxy authentification.

Your logs show : 

[https://api.dailymotion.com/oauth/token] >>> grant_type=password&client_id=85d31f49e014fcb19018&client_secret=39a375b1f954275f99a4c63eb929f74748f902dc&scope=read+write+delete+manage_videos&username=**root**&password=XXX

The user root is not a valid dailymotion's OAuth username.
username field must be an email.

Regards.

**Comment by oguzdelioglu** [comment] 2018-11-22 20:55
> Hi @oguzdelioglu,
> 
> I think your variables $login and $password are overwritten with your proxy credentials.
> 
> Can you check in your code that the names of these variables are not the same for the dailymotion authentification and the proxy authentification.
> 
> Your logs show :
> 
> [https://api.dailymotion.com/oauth/token] >>> grant_type=password&client_id=85d31f49e014fcb19018&client_secret=XXX&scope=read+write+delete+manage_videos&username=**root**&password=XXX
> 
> The user root is not a valid dailymotion's OAuth username.
> username field must be an email (the email that you use when you log in on [www.dailymotion.com](http://www.dailymotion.com)).
> 
> Regards.

I changed variables.

new result


:>>> [https://api.dailymotion.com/oauth/token] >>> grant_type=password&client_id=85d31f49e014fcb19018&client_secret=39a375b1f954275f99a4c63eb929f74748f902dc&scope=read+write+delete+manage_videos&username=zavihuliva%40mailzi.ru&password=Km820200%40 <<< [https://api.dailymotion.com/oauth/token] <<< HTTP/1.1 200 OK Content-Security-Policy-Report-Only: default-src https: blob: wss: data: android-webview-video-poster: android-webview: chrome-extension: safari-extension: 'unsafe-eval' 'unsafe-inline'; report-uri https://www.dailymotion.com/content_security_policy_report_uri Server: DMS/1.0.42 X-DM-BackNode: web-554.adm.dc3.dailymotion.com:80 Vary: X-DM-SSL,Accept-Encoding Cache-Control: no-store, stale-if-error=900 Content-Type: application/json Content-Security-Policy: upgrade-insecure-requests Access-Control-Expose-Headers: X-DM-BackNode-Response-Time Date: Thu, 22 Nov 2018 20:55:25 GMT X-DM-LB-IP: 195.8.215.129 X-DM-LB-Name: lb-07 X-DM-Random-Number: 1055507 X-DM-BackNode-Response-Time: 353 X-DM-Cache-Status: MISS X-Protected-By: Sqreen X-Dm-Page: ru.html.api_oauth_token X-DM-Edge: DMParis Content-Length: 221 {"access_token":"bzNUUAZMUxoFFRESCQRGQ1hbHghXTBEEDF1CCFteHxFS","token_type":"Bearer","expires_in":36000,"refresh_token":"247cae8f49d40cd53e3d490cf9111ded9e33ace2","scope":"delete manage_videos read write","uid":"x1pbckr"}
Fatal error: Uncaught DailymotionAuthException: Invalid token server response: HTTP/1.1 200 OK Content-Security-Policy-Report-Only: default-src https: blob: wss: data: android-webview-video-poster: android-webview: chrome-extension: safari-extension: 'unsafe-eval' 'unsafe-inline'; report-uri https://www.dailymotion.com/content_security_policy_report_uri Server: DMS/1.0.42 X-DM-BackNode: web-554.adm.dc3.dailymotion.com:80 Vary: X-DM-SSL,Accept-Encoding Cache-Control: no-store, stale-if-error=900 Content-Type: application/json Content-Security-Policy: upgrade-insecure-requests Access-Control-Expose-Headers: X-DM-BackNode-Response-Time Date: Thu, 22 Nov 2018 20:55:25 GMT X-DM-LB-IP: 195.8.215.129 X-DM-LB-Name: lb-07 X-DM-Random-Number: 1055507 X-DM-BackNode-Response-Time: 353 X-DM-Cache-Status: MISS X-Protected-By: Sqreen X-Dm-Page: ru.html.api_oauth_token X-DM-Edge: DMParis Content-Length: 221 {"access_token":"bzNUUAZMUxoFFRESCQRGQ1hbHghXTBEEDF1CCFteHxFS","token_type":"Bearer","expires_in":36000,"refres in C:\laragon\www\modules\sdk\Dailymotion.php on line 732

**Comment by SuperToma** [comment] 2018-11-23 09:44
Hi @oguzdelioglu, 

What is your PHP version ? 
`php -v`

Your call is correct, the server's answer too.
I suppose your PHP version does not support variable assignment in the function json_decode (but I'm not sure)

Can you dump some variables in the file Dailymotion.php ?

Before the line 730 (after the json_decode function) add : 
`var_dump($response, json_last_error());`

And please do not paste your password, client_secret, access_token and refresh_token here, in this case your account can be used by somebody else :)

Regards,

**Comment by oguzdelioglu** [comment] 2018-11-23 11:50
> Hi @oguzdelioglu,
> 
> What is your PHP version ?
> `php -v`
> 
> Your call is correct, the server's answer too.
> I suppose your PHP version does not support variable assignment in the function json_decode (but I'm not sure)
> 
> Can you dump some variables in the file Dailymotion.php ?
> 
> Before the line 730 (after the json_decode function) add :
> `var_dump($response, json_last_error());`
> 
> And please do not paste your password, client_secret, access_token and refresh_token here, in this case your account can be used by somebody else :)
> 
> Regards,

PHP 7.2.11

Since it is a demo account, it is not important to steal this information :)

json error number:4

**Comment by SuperToma** [comment] 2018-11-23 14:19
And the `var_dump($response);`, does it show something ?

**Comment by oguzdelioglu** [comment] 2018-11-23 17:41
> And the `var_dump($response);`, does it show something ?

empty result

**Comment by oguzdelioglu** [comment] 2018-11-25 05:17
Still empty result

**Comment by SuperToma** [comment] 2018-11-26 09:47
Hi ! 

Your problem is very strange, you're the first one with this case.

In the file Dailymotion.php, line 720 can you replace this code : 

```        
        $result = json_decode(
            $response = $this->httpRequest(
                $this->oauthTokenEndpointUrl,
                $args,
                null,
                $statusCode,
                $responseHeaders,
                true
            ),
            true
        );
```


By this one : 

```
        $response = $this->httpRequest(
            $this->oauthTokenEndpointUrl,
            $args,
            null,
            $statusCode,
            $responseHeaders,
            true
        );
        var_dump('Response : ', $response);

        $result = json_decode($response);
        var_dump('Result : ', $result);
```

It will be great to receive the 2 var_dump too :)

Regards,

**Comment by oguzdelioglu** [comment] 2018-11-27 01:43
> Hi !
> 
> Your problem is very strange, you're the first one with this case.
> 
> In the file Dailymotion.php, line 720 can you replace this code :
> 
> ```
>         $result = json_decode(
>             $response = $this->httpRequest(
>                 $this->oauthTokenEndpointUrl,
>                 $args,
>                 null,
>                 $statusCode,
>                 $responseHeaders,
>                 true
>             ),
>             true
>         );
> ```
> By this one :
> 
> ```
>         $response = $this->httpRequest(
>             $this->oauthTokenEndpointUrl,
>             $args,
>             null,
>             $statusCode,
>             $responseHeaders,
>             true
>         );
>         var_dump('Response : ', $response);
> 
>         $result = json_decode($response);
>         var_dump('Result : ', $result);
> ```
> It will be great to receive the 2 var_dump too :)
> 
> Regards,



Example Proxy: 185.155.233.208:4045

PHP Result
>>> [https://api.dailymotion.com] >>> stdClass Object ( [call] => GET /file/upload [args] => Array ( ) ) <<< [https://api.dailymotion.com] <<< HTTP/1.1 200 OK Content-Security-Policy-Report-Only: default-src https: blob: wss: data: android-webview-video-poster: android-webview: chrome-extension: safari-extension: 'unsafe-eval' 'unsafe-inline'; report-uri https://www.dailymotion.com/content_security_policy_report_uri Server: DMS/1.0.42 X-DM-BackNode: web-680.adm.dc3.dailymotion.com:80 Vary: X-DM-SSL,Accept-Encoding Cache-Control: no-cache, must-revalidate, stale-if-error=900 Content-Type: application/json; charset=UTF-8 Access-Control-Expose-Headers: Date, X-DM-BackNode-Response-Time, X-DM-Edge, X-DM-Cache-Status, X-Served-By, X-DM-BackNode-Response-Time Content-Security-Policy: upgrade-insecure-requests Date: Tue, 27 Nov 2018 01:37:34 GMT X-DM-LB-IP: 195.8.215.129 Expires: Fri, 01 Jan 2010 05:00:00 GMT X-DM-LB-Name: lb-07 X-DM-Random-Number: 6545220 Access-Control-Allow-Origin: * X-DM-BackNode-Response-Time: 19 X-Robots-Tag: noindex X-Frame-Options: DENY X-DM-Cache-Status: MISS X-Protected-By: Sqreen Access-Control-Allow-Headers: Content-Type, Authorization Access-Control-Allow-Methods: GET, POST, DELETE X-Dm-Page: ru.json.advanced_api X-DM-Edge: DMParis Content-Length: 254 {"result":{"upload_url":"http:\/\/upload-01.dc3.dailymotion.com\/upload?uuid=2393d791b174358fc5d46e7d6c45666a&seal=f30c32a5d912b7451f63873276341fee","progress_url":"http:\/\/upload-01.dc3.dailymotion.com\/progress?uuid=2393d791b174358fc5d46e7d6c45666a"}} 
Fatal error: Uncaught exception 'DailymotionApiException' with message 'Invalid API server response' in C:\xampp\htdocs\modules\sdk\Dailymotion.php:434 Stack trace: #0 C:\xampp\htdocs\modules\sdk\Dailymotion.php(356): Dailymotion->call('GET /file/uploa...', Array) #1 C:\xampp\htdocs\modules\sdk\Dailymotion.php(326): Dailymotion->get('/file/upload', Array) #2 C:\xampp\htdocs\modules\upload5.php(84): Dailymotion->uploadFile('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\modules\sdk\Dailymotion.php on line 434



I uploaded my dailymotion.php

https://paste.ofcode.org/5AzQbAMmFXfjk3FcGqcFHq



this problem is very strange.

The project can continue if you can solve.
Thanks.

**Comment by nicoferron** [comment] 2018-11-27 14:46
Hello @oguzdelioglu ,
I replaced all the json_decode occurrences in this version of the Dailymotion.php: https://paste.ofcode.org/VyuAzpQ7SaA7XLdxfG8VJy

Could you try your project with it ? 

Regards.

**Comment by oguzdelioglu** [comment] 2018-11-27 17:53
> Hello @oguzdelioglu ,
> I replaced all the json_decode occurrences in this version of the Dailymotion.php: https://paste.ofcode.org/VyuAzpQ7SaA7XLdxfG8VJy
> 
> Could you try your project with it ?
> 
> Regards.

185.155.233.208:4045

string(39) "https://api.dailymotion.com/oauth/token" 
Fatal error: Uncaught exception 'DailymotionAuthException' with message 'Invalid token server response: HTTP/1.1 200 OK Content-Security-Policy-Report-Only: default-src https: blob: wss: data: android-webview-video-poster: android-webview: chrome-extension: safari-extension: 'unsafe-eval' 'unsafe-inline'; report-uri https://www.dailymotion.com/content_security_policy_report_uri Server: DMS/1.0.42 X-DM-BackNode: web-599.adm.dc3.dailymotion.com:80 Vary: X-DM-SSL,Accept-Encoding Cache-Control: no-store, stale-if-error=900 Content-Type: application/json Content-Security-Policy: upgrade-insecure-requests Access-Control-Expose-Headers: X-DM-BackNode-Response-Time Date: Tue, 27 Nov 2018 17:49:24 GMT X-DM-LB-IP: 195.8.215.129 X-DM-LB-Name: lb-09 X-DM-Random-Number: 9210464 X-DM-BackNode-Response-Time: 364 X-DM-Cache-Status: MISS X-Protected-By: Sqreen X-Dm-Page: ru.html.api_oauth_token X-DM-Edge: DMParis Content-Length: 221 {"access_token":"bnBbRgYPHhVEBxMaRExfGQwRDBgCGkQMBUQLEllCCAcG","token_type":"Bearer"," in C:\xampp\htdocs\modules\sdk\Dailymotion.php on line 734

Could the proxy be a problem?

I can upload without using a proxy but when I use a proxy, it gives an error as above.

**Comment by SuperToma** [comment] 2018-11-28 09:50
Hi,

Can you send us a proxy credentials sample ? (If we can connect).
Your proxy currently reply 403 on connection : 
`Received HTTP code 403 from proxy after CONNECT`

I think by email is better : Thomas.HAMOU@dailymotion.com

We would like to reproduce the problem for a better understanding, to give you a solution and improve the SDK :) 

Regards,

**Comment by SuperToma** [comment] 2018-11-29 16:21
Hi @oguzdelioglu !

Thank you really much for letting us test the code on your platform.
And we understood the problem !

The response of your proxy is not so valid.
Here is an example : 
`HTTP/1.1 200 Connection established
 
HTTP/1.1 200 OK
Content-Security-Policy-Report-Only: default-src https: blob: wss: data: android-webview-video-poster: android-webview: chrome-extension: safari-extension: 'unsafe-eval' 'unsafe-inline'; report-uri https://www.dailymotion.com/content_security_policy_report_uri
Server: DMS/1.0.42
X-DM-BackNode: web-577.adm.dc3.dailymotion.com:80
Vary: X-DM-SSL,Accept-Encoding
Cache-Control: no-store, stale-if-error=900
Content-Type: application/json
Content-Security-Policy: upgrade-insecure-requests
Access-Control-Expose-Headers: X-DM-BackNode-Response-Time
Date: Thu, 29 Nov 2018 15:55:49 GMT
X-DM-LB-IP: 195.8.215.129
X-DM-LB-Name: lb-07
X-DM-Random-Number: 7102740
X-DM-BackNode-Response-Time: 332
X-DM-Cache-Status: MISS
X-Protected-By: Sqreen
X-Dm-Page: ru.html.api_oauth_token
X-DM-Edge: DMParis
Content-Length: 221
 
{"access_token":"***","token_type":"Bearer","expires_in":36000,"refresh_token":"***","scope":"delete manage_videos read write","uid":"x27jqs5"}`

A "valid" HTTP message must be like : 

1. HTTP headers
2. 2 lines breaks (CRLF)
3. The body message

The proxy response contains 2 headers (instead of one).
The second header is considered as a part of the body message.
Then the json_decode function fails as the headers are not json compliant.

I think you must find a way to remove the first header (added by your proxy) : 
`HTTP/1.1 200 Connection established`
(in your proxy configuration I guess)

We let 3 lines of debug in the file Dailymotion.php line 873 if you want to debug.

Regards,

**Comment by nicoferron** [comment] 2018-12-03 09:30
Hi @oguzdelioglu,

Is it ok for you ? :) 

I think the issue can be closed as we demystify the problem.

Regards,

**Closed** 2018-12-18 16:22 UTC
