### ISSUE TITLE
Could not resolve host: api.dailymotion.com

### ISSUE THREAD

**Issue by TaktakTaktouk** [dailymotion/dailymotion-sdk-php#66] opened 2020-08-11 17:09 UTC
I use the API for two years and everything is ok. but today I start seeing this error:
`Could not resolve host: api.dailymotion.com`
wat is wrong, please? My server is ok and SSL too.

**Comment by nicoferron** [comment] 2020-08-12 09:06
Hello @TaktakTaktouk,
Is `nslookup api.dailymotion.com` succeed?
Are you experiencing this issue on all your API calls?
It's maybe due to a latency spike in your geographical zone, you could try to up the timeout value of the SDK [here](https://github.com/dailymotion/dailymotion-sdk-php/blob/master/Dailymotion.php#L92) and [here](https://github.com/dailymotion/dailymotion-sdk-php/blob/master/Dailymotion.php#L86)

**Comment by TaktakTaktouk** [comment] 2020-08-12 09:18
Thank you for you answer.
My server is based in France and it uses the Cloudflare DNS server. 
I already increased the timeout of the curl request and still getting the same problem: _Resolving timed out after 5514 milliseconds_
I have this issue only with the Dailymotion server. for example, when I try to reach Google or Vimeo server the response is very fast

**Comment by nicoferron** [comment] 2020-08-12 11:51
Do you confirm that api.dailymotion.com is not reachable at all on your side and it's not related to a specific API call?
What is the result of your `nslookup`?

**Comment by TaktakTaktouk** [comment] 2020-08-12 12:08
@nicoferron 
```
nslookup api.dailymotion.com
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find api.dailymotion.com: SERVFAIL
```
What does that mean, please?

**Comment by TaktakTaktouk** [comment] 2020-08-12 12:14
it seems that I was banned by dailymotion.com. Did you know why and how to fix it, please?

**Comment by nicoferron** [comment] 2020-08-13 09:21
Your DNS fails to resolve api.dailymotion.com
I tried with Cloudflare DNS (1.1.1.1 & 1.0.0.1) and wasn't able to reproduce.
Did you change something recently in your network configuration?

The SDK will not be able to work properly without DNS resolving, please check your DNS configuration

**Comment by TaktakTaktouk** [comment] 2020-08-13 10:56
I didn't change anything but now everything seems to work properly: DNS, CURL, Nslookup...
but when I try to upload a video I always get the same error: _This video has exceeded maximum duration allowed_
I have this error since yesterday even with a video of 8 minutes...

**Comment by nicoferron** [comment] 2020-08-13 12:29
Can you please fill a support request about this different issue [here](https://faq.dailymotion.com/hc/en-us/requests/new?ticket_form_id=39467#new-request) 
Provide as much information as you can in order to identify the source of the problem (account, API key, file information, ...)

**Closed by nicoferron** 2020-08-13 12:29 UTC
